"""LITE-safe slice of the vulnerability catalog metadata.

This module is the **single source of truth** for the non-sensitive,
open-source-shippable slice of ``VULN_CATALOG`` -- the per-finding-key
``severity``, ``title`` and ATT&CK ``mitre`` mapping. It lives under
``adscan_core`` so it survives the LITE image strip (``adscan_internal/pro``
and ``reporting`` are physically removed from the LITE runtime) and is
importable from any tier.

The full ``VULN_CATALOG`` (descriptions, remediation prose, impact text,
references) stays PRO-only in ``adscan_internal/pro/reporting/vuln_catalog.py``.
Only the three fields below are reproduced here -- ATT&CK technique IDs,
severity labels and human titles are all non-sensitive reference data.

Drift between this slice and the PRO catalog is caught at CI time by
``tests/unit/test_vuln_catalog_meta_drift.py``: every ``VULN_CATALOG`` key
must exist here with a byte-identical ``mitre`` list.

Entries whose ``mitre`` list is empty are findings that map to a hygiene /
configuration weakness with no single ATT&CK technique (e.g. obsolete OS,
krbtgt password age, machine-account-quota, RC4-only accounts, credentials
in LDAP attributes). They are kept in the slice so the keyset stays
complete; the Navigator builder simply emits no technique cell for them.
"""

from __future__ import annotations

from typing import Any

VULN_CATALOG_META: dict[str, dict[str, Any]] = {'kerberoast': {'severity': 'medium',
                'title': 'Kerberoasting',
                'mitre': [{'id': 'T1558.003',
                           'name': 'Steal or Forge Kerberos Tickets: Kerberoasting'}]},
 'asreproast': {'severity': 'medium',
                'title': 'AS-REP Roasting',
                'mitre': [{'id': 'T1558.004',
                           'name': 'Steal or Forge Kerberos Tickets: AS-REP Roasting'}]},
 'smb_null_domain': {'severity': 'medium',
                     'title': 'SMB Null Session Authentication on DC',
                     'mitre': [{'id': 'T1021.002',
                                'name': 'Remote Services: SMB/Windows Admin Shares'}]},
 'smb_guest_shares': {'severity': 'high',
                      'title': 'SMB Guest Session Share Access',
                      'mitre': [{'id': 'T1021.002',
                                 'name': 'Remote Services: SMB/Windows Admin Shares'}]},
 'ldap_anonymous': {'severity': 'medium',
                    'title': 'LDAP Anonymous Bind Enabled',
                    'mitre': [{'id': 'T1087.002', 'name': 'Account Discovery: Domain Account'}]},
 'ldap_security_posture': {'severity': 'high',
                           'title': 'LDAP Signing / Channel Binding Not Hardened',
                           'mitre': [{'id': 'T1557', 'name': 'Adversary-in-the-Middle'},
                                     {'id': 'T1557.001',
                                      'name': 'Adversary-in-the-Middle: LLMNR/NBT-NS Poisoning and '
                                              'SMB Relay'}]},
 'ntlmv1_enabled': {'severity': 'high',
                    'title': 'Domain Controller Accepts NTLMv1 Authentication',
                    'mitre': [{'id': 'T1557', 'name': 'Adversary-in-the-Middle'},
                              {'id': 'T1078', 'name': 'Valid Accounts'}]},
 'stale_passwords': {'severity': 'low',
                     'title': 'Passwords Predating Current Policy',
                     'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'stale_enabled_users': {'severity': 'low',
                         'title': 'Enabled Stale User Accounts Detected',
                         'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'tier0_highvalue_sprawl': {'severity': 'medium',
                            'title': 'Excessive Tier-0 / High-Value Identity Concentration',
                            'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'smb_relay_targets': {'severity': 'medium',
                       'title': 'Unsigned SMB Relay Targets Detected',
                       'mitre': [{'id': 'T1557.001',
                                  'name': 'Adversary-in-the-Middle: LLMNR/NBT-NS Poisoning and SMB '
                                          'Relay'}]},
 'smbv1_enabled': {'severity': 'medium',
                   'title': 'SMBv1 Protocol Enabled (Legacy Posture)',
                   'mitre': [{'id': 'T1021.002',
                              'name': 'Remote Services: SMB/Windows Admin Shares'}]},
 'smb_share_secrets': {'severity': 'high',
                       'title': 'Sensitive Data Found in SMB Shares',
                       'mitre': [{'id': 'T1552.001',
                                  'name': 'Unsecured Credentials: Credentials In Files'}]},
 'gpp_autologin': {'severity': 'high',
                   'title': 'GPP Autologin Credentials Exposed',
                   'mitre': [{'id': 'T1552.006',
                              'name': 'Unsecured Credentials: Group Policy Preferences'}]},
 'gpp_passwords': {'severity': 'high',
                   'title': 'GPP Passwords Exposed in SYSVOL',
                   'mitre': [{'id': 'T1552.006',
                              'name': 'Unsecured Credentials: Group Policy Preferences'}]},
 'laps': {'severity': 'medium',
          'title': 'LAPS Not Deployed on Domain Hosts (Posture)',
          'mitre': [{'id': 'T1078.003', 'name': 'Valid Accounts: Local Accounts'}]},
 'laps_readable': {'severity': 'high',
                   'title': 'LAPS Password Readable by Non-Admins',
                   'mitre': [{'id': 'T1555', 'name': 'Credentials from Password Stores'}]},
 'obsolete_computers': {'severity': 'high', 'title': 'Obsolete Operating Systems', 'mitre': []},
 'gmsa_readable': {'severity': 'high',
                   'title': 'gMSA Password Readable by Non-Admins',
                   'mitre': [{'id': 'T1555', 'name': 'Credentials from Password Stores'}]},
 'dcsync': {'severity': 'critical',
            'title': 'DCSync Privilege Abuse',
            'mitre': [{'id': 'T1003.006', 'name': 'OS Credential Dumping: DCSync'}]},
 'rbcd_exploitable': {'severity': 'high',
                      'title': 'Resource-Based Constrained Delegation Misconfiguration',
                      'mitre': [{'id': 'T1134.001',
                                 'name': 'Access Token Manipulation: Token Impersonation/Theft'}]},
 'force_change_password': {'severity': 'medium',
                           'title': 'Force Change Password Rights Assigned',
                           'mitre': [{'id': 'T1098', 'name': 'Account Manipulation'}]},
 'all_extended_rights': {'severity': 'medium',
                         'title': 'All Extended Rights Assigned',
                         'mitre': [{'id': 'T1098', 'name': 'Account Manipulation'}]},
 'adcs_esc1': {'severity': 'critical',
               'title': 'ADCS ESC1 - Misconfigured Certificate Template',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc2': {'severity': 'critical',
               'title': 'ADCS ESC2 - Any Purpose Certificate Template',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc3': {'severity': 'critical',
               'title': 'ADCS ESC3 - Enrollment Agent Template Abuse',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc4': {'severity': 'critical',
               'title': 'ADCS ESC4 - Vulnerable Certificate Template ACL',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc5': {'severity': 'critical',
               'title': 'ADCS ESC5 - Vulnerable CA Object ACL',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc6': {'severity': 'critical',
               'title': 'ADCS ESC6 - EDITF_ATTRIBUTESUBJECTALTNAME2 Enabled on CA',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc7': {'severity': 'critical',
               'title': 'ADCS ESC7 - Certificate Authority Privilege Abuse',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc8': {'severity': 'high',
               'title': 'ADCS ESC8 - NTLM Relay to Web Enrollment',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc9': {'severity': 'critical',
               'title': 'ADCS ESC9 - No Security Extension on Certificate Template',
               'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc10': {'severity': 'high',
                'title': 'ADCS ESC10 - Weak Certificate Mapping via Registry Settings',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc11': {'severity': 'high',
                'title': 'ADCS ESC11 - NTLM Relay to RPC Certificate Enrollment',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc13': {'severity': 'critical',
                'title': 'ADCS ESC13 - Issuance Policy with Group Link Abuse',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc14': {'severity': 'critical',
                'title': 'ADCS ESC14 - Weak Explicit Certificate Mapping Abuse',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'nopac': {'severity': 'critical',
           'title': 'noPac/sAMAccountName Spoofing (CVE-2021-42278 + CVE-2021-42287)',
           'mitre': [{'id': 'T1068', 'name': 'Exploitation for Privilege Escalation'},
                     {'id': 'T1558', 'name': 'Steal or Forge Kerberos Tickets'}]},
 'zerologon': {'severity': 'critical',
               'title': 'ZeroLogon (CVE-2020-1472)',
               'mitre': [{'id': 'T1210', 'name': 'Exploitation of Remote Services'}]},
 'printnightmare': {'severity': 'high',
                    'title': 'PrintNightmare Vulnerable Hosts Detected',
                    'mitre': [{'id': 'T1068', 'name': 'Exploitation for Privilege Escalation'}]},
 'ms17-010': {'severity': 'high',
              'title': 'MS17-010 (EternalBlue) Vulnerable Hosts Detected',
              'mitre': [{'id': 'T1210', 'name': 'Exploitation of Remote Services'}]},
 'webdav': {'severity': 'medium',
            'title': 'WebDAV Coercion Attack Surface Detected',
            'mitre': [{'id': 'T1187', 'name': 'Forced Authentication'}]},
 'dfscoerce': {'severity': 'medium',
               'title': 'DFSCoerce Authentication Coercion Primitive',
               'mitre': [{'id': 'T1187', 'name': 'Forced Authentication'}]},
 'mseven': {'severity': 'medium',
            'title': 'MS-EFSRPC Coercion Primitive (PetitPotam Variant)',
            'mitre': [{'id': 'T1187', 'name': 'Forced Authentication'}]},
 'petitpotam': {'severity': 'medium',
                'title': 'PetitPotam Authentication Coercion Primitive',
                'mitre': [{'id': 'T1187', 'name': 'Forced Authentication'}]},
 'printerbug': {'severity': 'medium',
                'title': 'PrinterBug (SpoolSample) Authentication Coercion Primitive',
                'mitre': [{'id': 'T1187', 'name': 'Forced Authentication'}]},
 'unconstrained_delegation': {'severity': 'high',
                              'title': 'Unconstrained Kerberos Delegation Enabled',
                              'mitre': [{'id': 'T1558',
                                         'name': 'Steal or Forge Kerberos Tickets'}]},
 'constrained_delegation': {'severity': 'medium',
                            'title': 'Constrained Kerberos Delegation Misconfiguration',
                            'mitre': [{'id': 'T1558', 'name': 'Steal or Forge Kerberos Tickets'}]},
 'password_not_req': {'severity': 'medium',
                      'title': 'Accounts with Password Not Required Flag',
                      'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'password_not_required': {'severity': 'low',
                           'title': 'Accounts with No Password Required (PASSWD_NOTREQD)',
                           'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'password_never_expires': {'severity': 'low',
                            'title': 'Accounts with Non-Expiring Passwords',
                            'mitre': [{'id': 'T1078', 'name': 'Valid Accounts'}]},
 'da_sessions': {'severity': 'high',
                 'title': 'Domain Admin Sessions on Non-Privileged Hosts',
                 'mitre': [{'id': 'T1078.002', 'name': 'Valid Accounts: Domain Accounts'}]},
 'krbtgt_pass': {'severity': 'critical',
                 'title': 'KRBTGT Password Exposure Detected',
                 'mitre': [{'id': 'T1558.001',
                            'name': 'Steal or Forge Kerberos Tickets: Golden Ticket'}]},
 'adcs_esc15': {'severity': 'high',
                'title': 'ADCS ESC15 — Schema Version 1 Authentication Abuse',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc16': {'severity': 'high',
                'title': 'ADCS ESC16 - Missing SID Security Extension on the CA',
                'mitre': [{'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'adcs_esc17': {'severity': 'high',
                'title': 'ADCS ESC17 - Server Authentication Certificate Abuse',
                'mitre': [{'id': 'T1557', 'name': 'Adversary-in-the-Middle'},
                          {'id': 'T1649', 'name': 'Steal or Forge Authentication Certificates'}]},
 'shadow_credentials_present': {'severity': 'high',
                                'title': 'Shadow Credentials (msDS-KeyCredentialLink) Present',
                                'mitre': [{'id': 'T1606.002',
                                           'name': 'Forge Web Credentials: SAML Tokens'}]},
 'krbtgt_password_age': {'severity': 'medium',
                         'title': 'krbtgt Account Password Not Rotated',
                         'mitre': []},
 'weak_password_policy': {'severity': 'medium',
                          'title': 'Weak Default Domain Password Policy',
                          'mitre': [{'id': 'T1110.003', 'name': 'Brute Force: Password Spraying'},
                                    {'id': 'T1110.002', 'name': 'Brute Force: Password Cracking'}]},
 'machine_account_quota_risk': {'severity': 'low',
                                'title': 'Machine Account Quota Allows Domain Join',
                                'mitre': []},
 'smb_v1_enabled': {'severity': 'high',
                    'title': 'SMBv1 Protocol Enabled',
                    'mitre': [{'id': 'T1210', 'name': 'Exploitation of Remote Services'}]},
 'smb_signing_disabled': {'severity': 'medium',
                          'title': 'SMB Signing Not Required',
                          'mitre': [{'id': 'T1557.001',
                                     'name': 'LLMNR/NBT-NS Poisoning and SMB Relay'}]},
 'rc4_only_accounts': {'severity': 'medium',
                       'title': 'RC4-Only Kerberos Accounts (No AES Support)',
                       'mitre': []},
 'credential_in_ldap_attribute': {'severity': 'high',
                                  'title': 'Credentials Found in LDAP Attributes',
                                  'mitre': []},
 'ntlm_authentication_accepted': {'severity': 'medium',
                                  'title': 'Domain Controller Accepts NTLM Authentication',
                                  'mitre': [{'id': 'T1557', 'name': 'Adversary-in-the-Middle'},
                                            {'id': 'T1557.001',
                                             'name': 'Adversary-in-the-Middle: LLMNR/NBT-NS '
                                                     'Poisoning and SMB Relay'},
                                            {'id': 'T1550.002',
                                             'name': 'Use Alternate Authentication Material: Pass '
                                                     'the Hash'}]},
 'ldaps_unavailable': {'severity': 'medium',
                       'title': 'LDAPS (LDAP over TLS) Not Available on Domain Controller',
                       'mitre': [{'id': 'T1040', 'name': 'Network Sniffing'},
                                 {'id': 'T1557.001',
                                  'name': 'Adversary-in-the-Middle: LLMNR/NBT-NS Poisoning and SMB '
                                          'Relay'}]},
 'kerberos_rc4_domain_accepted': {'severity': 'medium',
                                  'title': 'Domain Controller Accepts RC4 Kerberos Encryption',
                                  'mitre': [{'id': 'T1558.003',
                                             'name': 'Steal or Forge Kerberos Tickets: '
                                                     'Kerberoasting'},
                                            {'id': 'T1558.004',
                                             'name': 'Steal or Forge Kerberos Tickets: AS-REP '
                                                     'Roasting'}]},
 'kerberos_aes_not_forced': {'severity': 'medium',
                             'title': 'Domain Does Not Force AES Encryption for Kerberos',
                             'mitre': [{'id': 'T1558.003',
                                        'name': 'Steal or Forge Kerberos Tickets: Kerberoasting'}]}}

__all__ = ("VULN_CATALOG_META",)
